# ai_service/main.py - FastAPI mock AI service
from fastapi import FastAPI, Header, HTTPException
from pydantic import BaseModel
import os

app = FastAPI(title='Logy AI Service')

class AnalyzeRequest(BaseModel):
    description: str | None = None
    images: list[str] | None = None

@app.post('/analyze')
async def analyze(req: AnalyzeRequest, x_api_key: str = Header(None)):
    if os.getenv('AI_SERVICE_KEY') and x_api_key != os.getenv('AI_SERVICE_KEY'):
        raise HTTPException(status_code=401, detail='Invalid key')
    # Mock response - integrate real model later
    return {
        "title": "iPhone 15 Pro (Titanium)",
        "description": "Mock analysis result generated by Logy AI",
        "price": 105000,
        "category": "electronics",
        "specs": {"storage":"256GB","color":"Titanium"}
    }

if __name__ == '__main__':
    import uvicorn
    uvicorn.run('main:app', host='0.0.0.0', port=8000)
